### ISSUE TITLE
Error with PhantomJS

### ISSUE THREAD

**Issue by Lichtjaeger** [jon-hall/pm2-windows-service#13]
Hi,

I've builded a webservice with a pdf-export. Starting pm2 with cmd and all is working.

If I start pm2 as a service i got some errors with the pdf-creator.

marcbachmann/node-html-pdf#179

**Comment by jon-hall** [comment]
This looks like it's related to the issue of the service running under `LOCAL SYSTEM` by default, probably because the files or folders being accessed are inaccessible for that account; the simplest fix would probably be making sure access permissions are in place for the `LOCAL SYSTEM` account on all files/folders involved.

There's also currently an outstanding issue (#3) to make support for running the service under a different account easier, this has yet to be implemented in the package, but the user who posted the issue kindly put together a powershell script which gets the job done (https://github.com/jon-hall/pm2-windows-service/issues/3#issuecomment-171028296).  That script is geared to running the service as `LOCAL SERVICE`, but it may be possible to adapt it to run under the user you are currently able to run your application as.

If neither of these solve your issue, please post up a little more info on how I might reproduce the problem and I'll see what I can do, thanks.

**Comment by jon-hall** [comment]
Update on specifying service user - https://github.com/jon-hall/pm2-windows-service/issues/3#issuecomment-247784482.

**Comment by Lichtjaeger** [comment]
Sorry I can test this at the earliest 24.09.. Here is a [testproject](https://github.com/jon-hall/pm2-windows-service/files/478727/pdf.zip) if you want to run some tests your own.

**Comment by Lichtjaeger** [comment]
Tested with user "Administrator": no change. Tested with `--no-daemon`-flag doesn't work either.

I would think this is a phantom.js problem. So, you can close this if you want.
