### ISSUE TITLE
pm2-windows-services installs but fails to start

### ISSUE THREAD

**Issue by KrishnaMBhattarai** [jon-hall/pm2-windows-service#16]
Hello, 

I am having trouble making pm2-windows-service persist mainly on windows 7 machines. After installation, when I look at services.msc I can see that it is installed but not 'started'. It seems rather inconsistent. In some computers, installing the service a second time, seems to fix the issue, but in others no matter what I do, the service does not get started on its own. If I start it manually from services.msc and start my application and save it, later on I log back in only to find that pm2-windows-service has mysteriously failed to start. It is there, it is installed, but not started. 

How could we fix this issue? 
Any help would be much appreciated

Krishna

**Comment by KrishnaMBhattarai** [comment]
The following is some information that might be helpful. The versions that are installed are:

node v4.4.7
npm v2.15.8
pm2 2.0.15
pm2-windows-service 0.2.0

The log files under /node_modules/pm2-windows-service/src/daemon/
pm2.err
Sorry, this script requires pm2
Sorry, this script requires pm2
Sorry, this script requires pm2

pm2.out 
*\* This file was empty **

pm2.wrapper
2016-10-11 08:43:59 - Starting C:\Program Files\nodejs\node.exe --harmony "C:\Users\DatalakeSA\AppData\Roaming\npm\node_modules\pm2-windows-service\node_modules\node-windows\lib\wrapper.js" -f "C:\Users\DatalakeSA\AppData\Roaming\npm\node_modules\pm2-windows-service\src\service.js" -l "PM2" -g 0.25 -w 1 -r 3 -a n
2016-10-11 08:43:59 - Started 6044

pm2.xml
<service><id>pm2.exe</id><name>PM2</name><description></description><executable>C:\Program Files\nodejs\node.exe</executable><arguments>--harmony "C:\Users\DatalakeSA\AppData\Roaming\npm\node_modules\pm2-windows-service\node_modules\node-windows\lib\wrapper.js" -f "C:\Users\DatalakeSA\AppData\Roaming\npm\node_modules\pm2-windows-service\src\service.js" -l "PM2" -g 0.25 -w 1 -r 3 -a n</arguments><logmode>rotate</logmode></service>

PM2_HOME is set at:
C:\Users\Some_User\AppData\Roaming\npm\etc.pm2

**Comment by jon-hall** [comment]
Hi, thanks for the extra info - it seems like the service isn't starting due to it hitting the error found [here](https://github.com/jon-hall/pm2-windows-service/blob/591514d70d29be69b7a6155f0a1abbb8ca722eee/src/service.js#L26), caused by [the attempt to find your global pm2 directory](https://github.com/jon-hall/pm2-windows-service/blob/591514d70d29be69b7a6155f0a1abbb8ca722eee/src/common.js#L32) failing.

The simplest fix would be to manually specify your global pm2 directory by setting the (machine-level) environment variable `PM2_SERVICE_PM2_DIR` to the directory you have pm2 installed in.  Restart the service and hopefully that error will go away and it'll be able to start.

It would seem the underlying cause might be that pm2 isn't on your `PATH` for some reason which would cause the `shell.which` check to fail (or possibly, you have multiple pm2s on the `PATH`).

Let me know if the above doesn't resolve the issue for you and I'll try and see what else might be going on.

**Comment by KrishnaMBhattarai** [comment]
yes, PM2_SERVICE_PM2_DIR being pointed to the wrong user was the culprit. I was able to make things work by fixing that. 

Thank you!
