### ISSUE TITLE
Error: Unable to load PM2 JSON configuration file

### ISSUE THREAD

**Issue by kjetilhp** [jon-hall/pm2-windows-service#18]
env:
PM2_HOME=c:\apps\pm
PM2_SERVICE_PM2_DIR=C:\nodejs-v6\node_modules\pm2\index.js
PM2_SERVICE_SCRIPTS=c:/apps/pm/test-webservice-run.json
SET_PM2_HOME=true
SET_PM2_SERVICE_PM2_DIR=true
SET_PM2_SERVICE_SCRIPTS=true

`Error: Unable to load PM2 JSON configuration file (c:\apps\pm\test-webservice-run.json)
 at process_start_script (C:\nodejs-v6\node_modules\pm2-windows-service\src\service.js:62:19)
 at Array.forEach (native)
 at C:\nodejs-v6\node_modules\pm2-windows-service\src\service.js:45:33
 at C:\nodejs-v6\node_modules\pm2\lib\API.js:136:14
 at C:\nodejs-v6\node_modules\pm2\lib\Client.js:86:18
 at Timeout._onTimeout (C:\nodejs-v6\node_modules\pm2\lib\Client.js:309:19)
 at ontimeout (timers.js:365:14)
 at tryOnTimeout (timers.js:237:5)
 at Timer.listOnTimeout (timers.js:207:5)
C:\nodejs-v6\node_modules\pm2-windows-service\src\service.js:62
 throw new Error('Unable to load PM2 JSON configuration file (' + start_script + ')');`

Tried with / and double \ as path sep. but same error

The file is present in c:\apps\pm
Content:

```
{
  apps : [{
    name   : "test-webservice",
    script : "./index.js",
    watch  : true,
    cwd    : "c:/apps/pm2-test-services"
  }]
}
```

```
```

**Comment by jon-hall** [comment]
Hi, my apologies for not getting back to you sooner on this, I've been a little overrun lately.  I finally got a chance to reproduce this setup locally and figure out what might be going wrong.  Using `node@6.9.1` and `pm2@2.0.19`, I was able to get this running by altering your `test-webservice-run.json` - I believe the problem is that it currently isn't valid JSON (the keys need double-quotes around them), and so the `require` call to load it is failing.

Using:

``` json
{
  "apps" : [{
    "name"   : "test-webservice",
    "script" : "./index.js",
    "watch"  : true,
    "cwd"    : "c:/apps/pm2-test-services"
  }]
}
```

The service was starting fine and running the test application I located at `c:/apps/pm2-test-services/index.js`.  Please let me know if this still doesn't get your service running smoothly.

**Comment by kjetilhp** [comment]
oh.. my bad :( I was so focused on the message that said it couldn't load the config file that I didn't notice the bad formatting. Now it works, thanks!
