### ISSUE TITLE
resurrect not being done after server reboot

### ISSUE THREAD

**Issue by user3160** [jon-hall/pm2-windows-service#19]
Hello, here is the sequence:
1. `npm i pm2 -g`
2. `npm i pm2-windows-service -g`
3. manually create PM2_HOME pointing to `c:\users\admin\.pm2`
4. call `pm2-service-install` answer No to environment setup
5. launch node services, call `pm2 save`
6. reboot server - pm2 service is running, no nodejs services are up
7. calling `pm2 ls` gives an empty table
8. calling `pm2 resurrect` manually successfully restores the nodejs processes.

What I'm doing wrong?

PM2 v.2.0.19
Nodejs 6.9.1 32bit
pm2-windows-service - latest

**Comment by jon-hall** [comment]
Hi, everything there looks reasonable and should be enough for the service to relaunch the process dump.  The most likely causes are:
- Is the `PM2_HOME` env var set on the machine-level rather than the user (it should be set at the machine-level, otherwise the service won't see it and will use the default location)?  (your issue does potentially seem like the process dump file you created by calling `pm2 save` isn't in the location the service is using for `PM2_HOME`).
- Another thing that is currently required is interacting with `pm2` only via an administrative command prompt - doing this to list, start, and `save` your processes might also remedy the issue; if you hadn't done it that way initially.
- Finally, with `PM2_HOME` being in a user directory it's possible the service user (`LOCALSYSTEM` by default) might have access issues - this would usually show up as errors in the logs at `<pm2-windows-service install directory>/src/daemon`.

I haven't thoroughly tested the service since `pm2@2` was released (nor since `node@6` hit LTS), so let me know if none of the above help you and I'll try and find some time to do further testing to see if I can recreate the issue and figure out what's going wrong.

**Comment by user3160** [comment]
Oooh, the PM2_HOME was set on user level, fixed it to be on machine level, thank you so much, sorry for such an obvious mistake.

Thanks for your promp reply again!
