### ISSUE TITLE
App had too many unstable restarts

### ISSUE THREAD

**Issue by SPJames** [jon-hall/pm2-windows-service#20]
I ran the install (pm2-service-install) and set all the variables. 
I made sure PM2_Home is a absolute path.
My ecosystem.config.js has the following content:
`module.exports = {
  apps : [{
    name        : "TelecomProvider",
    script      : "MyPath\\app.js",
    watch       : false
    instances   : 4,
    exec_mode   : "cluster"
  }]
}`

However when starting the service I get the error that it had to many unstable restarts.
Here is a snippet from the logfile
> 2016-11-25 13:57:52: Launching in no daemon mode
> 2016-11-25 13:58:00: Starting execution sequence in -fork mode- for app name:TelecomProvider id:0
> 2016-11-25 13:58:00: App name:TelecomProvider id:0 online
> 2016-11-25 13:58:01: App [TelecomProvider] with id [0] and pid [12120], exited with code [1] via signal [SIGINT]
> 2016-11-25 13:58:01: Starting execution sequence in -fork mode- for app name:TelecomProvider id:0
> 2016-11-25 13:58:01: App name:TelecomProvider id:0 online
> 2016-11-25 13:58:02: App [TelecomProvider] with id [0] and pid [15908], exited with code [1] via signal [SIGINT]
> 2016-11-25 13:58:02: Starting execution sequence in -fork mode- for app name:TelecomProvider id:0
> 2016-11-25 13:58:02: App name:TelecomProvider id:0 online
> 2016-11-25 13:58:03: App [TelecomProvider] with id [0] and pid [14020], exited with code [1] via signal [SIGINT]
> 2016-11-25 13:58:03: Starting execution sequence in -fork mode- for app name:TelecomProvider id:0
> 2016-11-25 13:58:03: App name:TelecomProvider id:0 online
> 2016-11-25 13:58:03: App [TelecomProvider] with id [0] and pid [15184], exited with code [1] via signal [SIGINT]
> 2016-11-25 13:58:03: Script Mypath\app.js had too many unstable restarts (16). Stopped. "errored"

The app itself is stable and using just pm2 is working fine.

Any idea what is going wrong?

**Comment by jon-hall** [comment]
Hi, sorry that you're getting issues with this; as far as I'm aware the 'unstable restarts' issue would only arise if your app was crashing at start-up.  The reason this happens when running under the service, but not when manually run using `pm2`, is likely due to the fact that (by default) the service runs under the `LOCAL SYSTEM` user, and this can cause permissions issues etc.

You might find that manually changing the user the service runs under (from the windows `Services` manager) to a more suitable user may fix the issue; though if you'd rather diagnose what's going on, more detailed logging is probably required.

The pm2 error logs, as you can see, don't give a huge amount of info on exactly what's going on - if you have error logs from your application itself, they might contain more info.  If you don't have any log output currently, you can get pm2 to log `stdout` and `stderr` to disk by adding this to the config for your app in `ecosystem.config.js`:
```js
    'error_file' : './log/std-err.log',
    'out_file' : './log/std-out.log'
```

Hopefully restarting the service and checking the error logs for your app might then give some clues as to what is happening when it tries to start.

If you want to post up any additional logs you can get from your app, version info for `node`, `npm`, `pm2`, and `pm2-windows-service`, along with (anonymised) values for your app location, `ecosystem.config.js` location, and `PM2_HOME` (your global `pm2` install directory and the result of `npm get prefix` run as administrator may also be helpful, if you haven't set `PM2_SERVICE_PM2_DIR`) - specifically what's of interest here is whether they are in folders which may have permissions issues (user folders, program files etc.).

I can then try and reproduce the issue and figure out what might be going wrong.

**Comment by SPJames** [comment]
Hello Jon,

Thanks for the reply, after some testing it seems to work!
