### ISSUE TITLE
Unable to install pm2 as a service

### ISSUE THREAD

**Issue by dragsssss** [jon-hall/pm2-windows-service#23]
Node version: 0.12.17
Win version: Windows Server 2012 R2 64-bit

Considering this is a different error that was experienced in this issue https://github.com/jon-hall/pm2-windows-service/issues/2

I know the minimum requirement is 4.0 for node but wondering if there's something obviously wrong with what I'm doing which is breaking it.

![image](https://cloud.githubusercontent.com/assets/520458/21669338/0bb34cc0-d35f-11e6-88c6-48206b6a231e.png)

Thanks.

**Comment by jon-hall** [comment]
Hi, unfortunately this is definitely due to using version `0.x` of node - the source code uses ES6 features (in this case object literal methods, e.g. `{ fn() { /*...*/ } }`) which node `< 4.x` doesn't support.

I've previously considered making the library compatible with older versions of node but feel upgrading is the right solution for a production environment; so all I could recommend is upgrade your node version if possible.  If you are unable to upgrade I'll consider that another +1 towards making the library backwards compatible to node `0.12.x` and can take a look into providing such support when I get an opportunity.

**Comment by dragsssss** [comment]
Ok no worries, thanks for your quick response. I'll have a look  at what we could do in upgrading the node version.
