### ISSUE TITLE
PM2 Service starts wrong app

### ISSUE THREAD

**Issue by ClintSchauff** [jon-hall/pm2-windows-service#31]
Hi Jon,

Strange issue here, hoping you can help me.  I was using a test application, myApp, that I had running in PM2.  You helped me get a Pm2 Windows Service up and running with that test application.  After that was working, I removed the app myApp by using PM2 Kill, then PM2 delete process.json(the config file I used to set it up).   I set up my Production application on this Development server and was able to get it up and running in PM2:
![image](https://user-images.githubusercontent.com/32966912/31908415-68dc8f1a-b7fc-11e7-8359-e2ca8f2aad4d.png)

Following your advice, I used JSONinstead of JSON5 to get the config file set up:
{
  "apps" : [{
    "name"      : "source",
    "script"    : "bin\\www",         // Script to be run
    "exec_mode" : "cluster",        // Allow your app to be clustered
    "instances" : 1,                // Optional: Scale your app by 4
    "args"      : "Node1",
    "max_memory_restart" : "100M"   // Opt
  },{
    "name"      : "source",
    "script"    : "bin\\www",         // Script to be run
    "exec_mode" : "cluster",        // Allow your app to be clustered
    "instances" : 1,                // Optional: Scale your app by 4
    "args"      : "Node2",
    "max_memory_restart" : "100M"   // Opt
  },{
    "name"      : "source",
    "script"    : "bin\\www",         // Script to be run
    "exec_mode" : "cluster",        // Allow your app to be clustered
    "instances" : 1,                // Optional: Scale your app by 4
    "args"      : "Node3",
    "max_memory_restart" : "100M"   // Opt
  },{
    "name"      : "source",
    "script"    : "bin\\www",         // Script to be run
    "exec_mode" : "cluster",        // Allow your app to be clustered
    "instances" : 1,                // Optional: Scale your app by 4
    "args"      : "Node4",
    "max_memory_restart" : "100M"   // Opt
  }
]}

Installed the service:

![image](https://user-images.githubusercontent.com/32966912/31908593-0dedd5e0-b7fd-11e7-8cf6-5b109fa96e27.png)

Then I check to see if the service is online using PM2 List:

![image](https://user-images.githubusercontent.com/32966912/31908644-35a693ba-b7fd-11e7-8b88-31574e86991d.png)

It shows that the service is still running myApp!  Any idea what I'm doing wrong?  I do see the "In-memory PM2 is out-of-date" message which I can't seem to get rid of even after running pm2 update.  I'm unsure whether or not that is related.

Thanks, Clint

**Comment by ClintSchauff** [comment]
Interestingly, if I run PM2 update then run PM2 List, I don't get the "in-memory" message:

![image](https://user-images.githubusercontent.com/32966912/31909475-dff90b52-b7ff-11e7-8e9d-b04287e19425.png)

If I then run PM2 Kill, and then start the service I get that message and it starts the wrong application.  I even tried completely removing the "myApp"  application from the machine and then recreating the service with my source2 application.  It once again runs fine in command line, but then the when I try to start the service, I get "myApp.exe could not be found".  Am I not removing the app from PM2 properly before trying to create a new service? 

Thanks again, Clint

**Comment by ClintSchauff** [comment]
Ok, well I am officially baffled by this.  I've deleted all of the pM2/pm2-windows-service env vars.  I've uninstalled and reinstalled both PM2 and pm2-windows-service but still every time I create a service using pm2-windows-service, it starts the same app.

**Comment by ClintSchauff** [comment]
UPDATE:  I finally was able to get this to work properly by completely uninstalling NodeJS and reinstalling.

**Comment by ClintSchauff** [comment]
Hi Jon,

Sorry for all of the messages.  I've solved original issue, but I think we have a different issue here which I mentioned above.  When I start PM2 using PM2-windows-service I get the following message, even after updating PM2.  If I run PM2 in command line, I don't get the message, but as soon as I start the service and run PM2 list, the message appears.  Thoughts?  Should I open this as a separate issue?

![image](https://user-images.githubusercontent.com/32966912/32003875-1493b666-b966-11e7-8656-f57896d22195.png)

**Comment by jon-hall** [comment]
Hi Clint,

Sorry I haven't been able to get back to you sooner - I've had a busy few days and never got a chance.  Apologies that you're getting so many issues with this - it does have a lot of caveats and can be a pain to get it all working sometimes unfortunately.

Your latest error sounds like the version of pm2 the service is running is `2.1.5` but the version that runs when you execute `pm2` on command line is `2.7.2`.

I believe the fix for this would be to make sure that you have `PM2_SERVICE_PM2_DIR` set at machine level (either do this manually or use the setup when installing).  It should point to the *folder* containing the version of `pm2` you want to use, e.g. `C:\Users\<user>\AppData\Roaming\npm\node_modules\pm2`.  Hopefully that'll get the service using the correct (updated) version of pm2.

I noticed though that you set an unusual value for `PM2_SERVICE_PM2_DIR` in the screenshot you included with the original post (`C:\WINDOWS\SYSTEM32\node_modules\pm2\index.js`) - this implies you've done `npm install pm2` as a *local* install in `SYSTEM32`?  If that's the case, then in order to interact with the same version of `pm2` on the command line (even when running as admin) you'd need to make sure you're using that version rather than the one that'll be in your default npm global install directory in your `PATH`.

You can do this in two ways I think:
```
SET PATH=C:\WINDOWS\SYSTEM32\node_modules\.bin;%PATH%
```
This will add the `node_modules\.bin` directory ahead of any other directories in your path for that terminal session - which would then mean the `pm2.cmd` in that directory will be the one you run by default.

Alternatively, you can just `cd` into `C:\WINDOWS\SYSTEM32\node_modules\.bin` and run `pm2`, which should use the version in that folder.

Let me know how this goes for you and if you're still getting issues I'll see what else I can do to help.

Cheers, Jon.

**Comment by ClintSchauff** [comment]
Hi Jon,

Thanks for all of your help! That did indeed fix my issue. I have another question for you if you don’t mind. I want to run 2 separate apps with 2 separate services but I haven’t been able to get that to work. The only way I’ve been able to get it to work is if I create a config file that starts 2 apps and then run it with a single service.

Here is how I’ve tried it:

Start and save the first app in PM2.
Create the service.
This all seems to work great.
image
![image](https://user-images.githubusercontent.com/32966912/32290762-08dabc72-bf09-11e7-8ef1-acdd5467ea15.png)


Now to start my other app:

switch to the c:\myApp directory
Start process.json (config file for myApp)
Pm2 save
Create the service with a new service name (myApp)
image
![image](https://user-images.githubusercontent.com/32966912/32290770-10a9bcbe-bf09-11e7-9055-e6c8d26a7301.png)


This seems to work…except that once I stop the services, run PM2 Kill and try to use the services to start the apps again, the apps don’t start. There are no errors, the services are running but the apps simply haven’t started:

image
![image](https://user-images.githubusercontent.com/32966912/32290780-153780fe-bf09-11e7-98dc-40c9cde49b09.png)


Is it possible to create 2 separate services for 2 separate apps?

CS

**Comment by jon-hall** [comment]
Hi Clint, it took me a little while to look into whether running multiple services is possible.  From what I can tell, it should be possible, but not with the current release of `pm2-windows-service`.

The main issue is how `pm2` itself works - it stores a pidfile in `%PM2_HOME%` which identifies the daemon process that all `pm2` commands should "connect" to (when the service is running, this pidfile will point to `pm2-windows-service/src/service.js`).

In order to run multiple services, you'd need them to have different values for `%PM2_HOME%`, so they operate on separate pidfiles and can have multiple usable daemons running simultaneously (one per service).  You'd also have the slight complexity of, when trying to interact with `pm2` via commandline, you'd need to set `%PM2_HOME%` to the correct value in each command shell, in order to interact with the right daemon for a specific service.

There's currently no way to make each service have a different value for `%PM2_HOME%`, however, I'm going to try and find some time in the next week to experiment with ways in which multiple services could be created, with each using a unique `%PM2_HOME%` value.  I'll report back here with anything I might find.

**Comment by ClintSchauff** [comment]
Sounds good, thanks for all your help Jon.

**Comment by jon-hall** [comment]
Closing this as the package is now deprecated, users should migrate to [`pm2-installer`](https://github.com/jessety/pm2-installer).
