### ISSUE TITLE
Install Error: "Windows service wrapper has stopped working"

### ISSUE THREAD

**Issue by badalyan** [jon-hall/pm2-windows-service#63]
Hi, I'm getting this error when installing on Windows 7 Pro (screenshot attached). When I run `services.msc`, I don't see the app on the list.

Any ideas on what's happening? @jon-hall 

<img width="894" alt="Screen Shot 2020-08-27 at 3 20 45 PM" src="https://user-images.githubusercontent.com/168454/91491155-42f10500-e879-11ea-8b21-900975811d0b.png">

**Comment by bwpoon** [comment]
I'm having this same issue while installing on Windows Server 2016.  Did you find out anything about this problem?

**UPDATE**
I installed .NET Framework 3.5 because of the caveat mentioned in the docs and restarted and then it worked.  I did this on several Windows Server 2016 machines and it was consistent.

**Comment by jon-hall** [comment]
Closing this as the package is now deprecated, users should migrate to [`pm2-installer`](https://github.com/jessety/pm2-installer).
